#<?xml version="1.0" encoding="UTF-8" ?>
#<routes xmlns="http://symfony.com/schema/routing"
#        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#        xsi:schemaLocation="http://symfony.com/schema/routing
#        http://symfony.com/schema/routing/routing-1.0.xsd">
#
#    <route id="event" controller="Manuxi\SuluEventBundle\Controller\Website\EventController::indexAction">
#        <path locale="de">/veranstaltungen/{id}/{slug}</path>
#        <path locale="en">/events/{id}/{slug}</path>
#    </route>
#
#</routes>
event:
    path:
        en: /events/{id}/{slug}
        de: /veranstaltungen/{id}/{slug}
    controller: Manuxi\SuluEventBundle\Controller\Website\EventController::indexAction
